### ISSUE TITLE
cannot resolve CNI plugins configuration path

### ISSUE THREAD

**Issue by shatvani** [siemens/edgeshark#33]
Hi,
I tried to install Edgeshark Docker Host on Ubuntu but I run into this error:
cannot resolve CNI plugins configuration path, reason: lstat /proc/5816/root/etc/cni: no such file or directory
Could you help me, please?
**UPDATE**
Sorry, I am tottaly new in this area.
So I can install Edgeshark if I have Kumernetes or other DevOps platforms managing my containers, right?

![image](https://github.com/siemens/edgeshark/assets/5359137/a3741d9c-0ce8-49da-9626-87b98f71a926)

**Comment by thediveo** [comment]
Yes, you can deploy the two Edgeshark services ghostwire and packetflix to k8s nodes. We currently do not provide any deployment resource files though. KinD is supported out of the box, but fully-blown k8s clusters need some node deployment work.

Please note that using Edgeshark on k8s clusters now require either containerd or cri-o with the "Evented PLEG API" being enabled in these container engines. 

The CNI log message can be safely ignored, it just indicates that no CNI config was seen.

**Comment by thediveo** [comment]
related to log error message: siemens/ghostwire#14.

**Comment by thediveo** [comment]
I'm closing this issue, as the CNI-related error log is already a dedicated issue. For questions please feel free to head over to the [discussions](https://github.com/siemens/edgeshark/discussions) section, or otherwise for issues open new ones.
