### ISSUE TITLE
fail to start gostwire

### ISSUE THREAD

**Issue by xiaopeng163** [siemens/edgeshark#52]
hi,

after running

```
$ wget -q --no-cache -O -   https://github.com/siemens/edgeshark/raw/main/deployments/wget/docker-compose.yaml   | docker compose -f - up
```

I got an error like

```
gostwire-1 exited with code 133
edgeshark-1  | DEBU[2024-03-15T22:16:11Z] handling "/w"...
edgeshark-1  | DEBU[2024-03-15T22:16:11Z] forwarding/reverse proxying to "http://gostwire.ghost-in-da-edge:5000/w"
edgeshark-1  | 2024/03/15 22:16:11 http: proxy error: dial tcp: lookup gostwire.ghost-in-da-edge on 127.0.0.11:53: no such host
gostwire-1   | INFO[2024-03-15T22:17:02Z] Gostwire "The Sequel" virtual network topology and configuration discovery service, version 2.4.1
gostwire-1   | INFO[2024-03-15T22:17:02Z] Copyright (c) Siemens AG 2018-2023
gostwire-1   | INFO[2024-03-15T22:17:02Z] available engine process detector plugins: containerd, cri-o, dockerd
gostwire-1   | INFO[2024-03-15T22:17:02Z] available socket activator detector plugins: systemd
gostwire-1   | assertion failed [!result.is_error]: Failed to create temporary file
gostwire-1   | (ThreadContextFcntl.cpp:84 create_tempfile)
```
and my docker/docker-compose version

```
demo@ubuntu2204:~$ docker version
Client: Docker Engine - Community
 Version:           25.0.3
 API version:       1.44
 Go version:        go1.21.6
 Git commit:        4debf41
 Built:             Tue Feb  6 21:13:09 2024
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          25.0.3
  API version:      1.44 (minimum version 1.24)
  Go version:       go1.21.6
  Git commit:       f417435
  Built:            Tue Feb  6 21:13:09 2024
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.28
  GitCommit:        ae07eda36dd25f8a1b98dfbf587313b99c0190bb
 runc:
  Version:          1.1.12
  GitCommit:        v1.1.12-0-g51d5e94
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
demo@ubuntu2204:~$ docker-compose version
Docker Compose version v2.25.0
demo@ubuntu2204:~$
```
anyone know the reason about this? Thanks

**Comment by thediveo** [comment]
That is very strange I can't place this, unfortunately: G(h)ostwire is deployed with a read-only topmost overlay on purpose. But the DNS lookup in the Edgeshark front-end service not finding the internal services network is also something strange. What kind of system are you deploying to?

**Comment by xiaopeng163** [comment]
Thanks for the reply. It is Orbstack VM, Ubuntu

https://orbstack.dev


TheDiveO ***@***.***>于2024年3月16日 周六09:27写道：

**Comment by thediveo** [comment]
I'm afraid that it isn't compatible, from how it crashes or services. Do you have user namespacing enabled? That must be off.

**Comment by xiaopeng163** [comment]
ok, I will try with another VM which not created by orbstack then. and btw, can I use edgeshark directly on M1 Mac?

**Comment by thediveo** [comment]
> and btw, can I use edgeshark directly on M1 Mac?

Using Docker Desktop I got reports from multiple users of Edgeshark working right out of the box on macos M1. For myself, I tested successfully with an older Intel macbook pro or so, and also got confirmation from colleagues.

> ok, I will try with another VM which not created by orbstack then.

I looked at their website, but I couldn't find any real details about their security claims (this is IMHO always a warning sign). I could suspect that they deviate from Docker's default configuration and that usually causes workload problems.

I would like to suggest that you might want to report this problem upstream to orbstack and see how they might react.

Docker is still more than a decade ahead in terms of deployment experience and giant user base. The problem with the original Docker Desktop and now all the panicking copycats is that they tackle a large percentage of undemanding workload developers, at the expense of more or less degraded diagnosability and vendor lock-in.

**Comment by c-hoeger** [comment]
I see the exact same error using Docker Desktop on an M3 Mac.

**Comment by thediveo** [comment]
Please open a new issue and give details. Thank you very much.

**Comment by thediveo** [comment]
can not reproduce with current Docker Desktop v4.33.0 on macos/Intel and Edgeshark v2.6.1.

**Comment by c-hoeger** [comment]
opened https://github.com/siemens/edgeshark/issues/62

**Comment by thediveo** [comment]
thanks to @c-hoeger we've got it working, the problem is due to `DOCKER_DEFAULT_PLATFORM=` being set to x86-64 images and then rosetta not handling read-only image deployments. Just deploy as follows to use the correct multi-arch images:

wget -q --no-cache -O - \
  https://github.com/siemens/edgeshark/raw/main/deployments/wget/docker-compose-localhost.yaml \
  | DOCKER_DEFAULT_PLATFORM= docker compose -f - up
