### ISSUE TITLE
Error by extcap pipe

### ISSUE THREAD

**Issue by hgoncal2** [siemens/edgeshark#9]
So i've been trying to solve this for a couple hours now,read every doc surrounding this issue,still can't seem to figure out how to solve it,or why it's happening.

So,the web UI works fine
![image](https://github.com/siemens/edgeshark/assets/101368171/28b10465-5a11-4d86-9572-72a0f5f4e18c)

First problem starts when in wireshark none of my containers show up
![image](https://github.com/siemens/edgeshark/assets/101368171/94bad21a-f90a-4e2b-88ec-af67b862b80e)
Of course pressing the "refresh" button doesn't do anything. Can't seem to find out why this is happening,since all my containers show up in the web UI.
Secondly,in the web UI,after trying to open up wireshark by clicking on the icon,and get this error.
![image](https://github.com/siemens/edgeshark/assets/101368171/ea20c776-91fa-4310-82f5-062ff88810ef)

I've installed the cshargextcap plugin,and i'm running the edgeshark docker compose project. 
Is there anything i'm missing?
Wireshark version 4.0.6

**Comment by thediveo** [comment]
Hi there, thank you very much for providing such useful details and sorry to hear you are having issues! Your third screenshot with the error message indicates that there seems to be a problem in your general system setup: "localhost" does not directly resolve to 127.0.0.1 (and ::1) as it is common, and using /etc/hosts, but instead your system tries to contact a DNS server (which it shouldn't in thise case) at 1.1.1.2, and this fails.

Can you try navigating to the Edgeshark ui using http://127.0.0.1:5001 instead and see if capturing then works?

As this is a system setup I've never seen, can you share some details about it? I've only seen a similar setup yesterday from a colleague, this is an Apple system, right?

**Comment by Silvanoc** [comment]
@thediveo looking at the paths of the 2nd screenshot, I'd say it's a Windows system, not a MacOS one.

**Comment by hgoncal2** [comment]
Sorry for not saying it in the beggining,yes it's windows + some wsl things. 
I've tried your suggestion of using 127.0.0.1 and now it works!
![image](https://github.com/siemens/edgeshark/assets/101368171/6fbacfaa-021e-4df2-aa0c-a0f61b4f3466)
The web UI wireshark thing also works fine. Weird how "localhost" was mapping to that address,even though my hosts file looks right
On wsl:
![image](https://github.com/siemens/edgeshark/assets/101368171/497787b7-9095-45f2-bcfc-b04ee6fdea7e)
![image](https://github.com/siemens/edgeshark/assets/101368171/675fc6a5-7fbb-4fb9-a4d3-c92c4daaa823)


And on windows:
![image](https://github.com/siemens/edgeshark/assets/101368171/ef350451-552e-4eea-95e1-c8b125358f6f)
![image](https://github.com/siemens/edgeshark/assets/101368171/8998d960-a591-466a-afb0-158c03629aa0)

**Comment by thediveo** [comment]
no worries, I mislead myself 😁 ... and I now have feedback from the first WSL2 user on top of that.

So this works for you, correct? I will close this issue as "has workaround" and document this. Feel free to reopen or create a new issue if you hit this again or something else.

**Comment by thediveo** [comment]
I've finally managed to install WSL2, or rather install it twice, as the first install was broken for whatever reason. I've applied the fix in https://github.com/microsoft/WSL/issues/5420 to avoid having /etc/resolv.conf getting recreated all the time and set static upstream DNS servers. This way, "localhost" works for me. Somehow your installation seems to maybe suffer from similar resolver configuration issues...?

**Comment by hgoncal2** [comment]
> I've finally managed to install WSL2, or rather install it twice, as the first install was broken for whatever reason. I've applied the fix in [microsoft/WSL#5420](https://github.com/microsoft/WSL/issues/5420) to avoid having /etc/resolv.conf getting recreated all the time and set static upstream DNS servers. This way, "localhost" works for me. Somehow your installation seems to maybe suffer from similar resolver configuration issues...?

Sorry for the late reply.I've tried the fix you've described and still doesn't work with "localhost".
This is my resolv.conf file
![image](https://github.com/siemens/edgeshark/assets/101368171/942e0412-fa4a-4662-ae2f-c703142f6278)
And i'm getting the same errors as described in the OP.

**Comment by thediveo** [comment]
One thing I noticed is in case of Docker Desktop you'll need to deinstall any previous Docker installation, as Docker Desktop integrates its own files into your distro. This took me some time to diagnose why this didn't work; but you seem to face a different issue with your WSL2 setup -- so just noting that just in case.
